namespace Microsoft.CodeAnalysis.VisualBasic
{
	internal class CustomSymbolDisplayFormatter
	{
		internal static readonly SymbolDisplayFormat QualifiedNameFormat = new SymbolDisplayFormat(SymbolDisplayGlobalNamespaceStyle.Omitted, SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces, SymbolDisplayGenericsOptions.IncludeTypeParameters, SymbolDisplayMemberOptions.IncludeParameters | SymbolDisplayMemberOptions.IncludeContainingType, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayParameterOptions.IncludeParamsRefOut | SymbolDisplayParameterOptions.IncludeType | SymbolDisplayParameterOptions.IncludeName | SymbolDisplayParameterOptions.IncludeDefaultValue, SymbolDisplayPropertyStyle.NameOnly, SymbolDisplayLocalOptions.None, SymbolDisplayKindOptions.None, SymbolDisplayMiscellaneousOptions.UseSpecialTypes | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

		internal static readonly SymbolDisplayFormat WithContainingTypeFormat = new SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.TypeQualificationStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.GenericsOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MemberOptions | SymbolDisplayMemberOptions.IncludeContainingType, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayFormat.VisualBasicErrorMessageFormat.ParameterOptions, SymbolDisplayPropertyStyle.NameOnly, SymbolDisplayLocalOptions.None, SymbolDisplayFormat.VisualBasicErrorMessageFormat.KindOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions);

		internal static readonly SymbolDisplayFormat ErrorMessageFormatNoModifiersNoReturnType = new SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.TypeQualificationStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.GenericsOptions, SymbolDisplayMemberOptions.IncludeExplicitInterface | SymbolDisplayMemberOptions.IncludeParameters | SymbolDisplayMemberOptions.IncludeContainingType, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayFormat.VisualBasicErrorMessageFormat.ParameterOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.PropertyStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.LocalOptions, SymbolDisplayKindOptions.None, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions);

		internal static readonly SymbolDisplayFormat ErrorNameWithKindFormat = new SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayTypeQualificationStyle.NameOnly, SymbolDisplayFormat.VisualBasicErrorMessageFormat.GenericsOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MemberOptions, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayFormat.VisualBasicErrorMessageFormat.ParameterOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.PropertyStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.LocalOptions, SymbolDisplayKindOptions.IncludeNamespaceKeyword | SymbolDisplayKindOptions.IncludeTypeKeyword, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions);

		internal static readonly SymbolDisplayFormat DelegateSignatureFormat = new SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.TypeQualificationStyle, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.GenericsOptions, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.MemberOptions, SymbolDisplayDelegateStyle.NameAndSignature, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.ParameterOptions, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.PropertyStyle, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.LocalOptions, SymbolDisplayKindOptions.IncludeNamespaceKeyword | SymbolDisplayKindOptions.IncludeTypeKeyword, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions);

		internal static readonly SymbolDisplayFormat ShortWithTypeArgsFormat = new SymbolDisplayFormat(SymbolDisplayFormat.ShortFormat.GlobalNamespaceStyle, SymbolDisplayFormat.ShortFormat.TypeQualificationStyle, SymbolDisplayGenericsOptions.IncludeTypeParameters, SymbolDisplayFormat.ShortFormat.MemberOptions, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayFormat.ShortFormat.ParameterOptions, SymbolDisplayFormat.ShortFormat.PropertyStyle, SymbolDisplayFormat.ShortFormat.LocalOptions, SymbolDisplayFormat.ShortFormat.KindOptions, SymbolDisplayFormat.ShortFormat.MiscellaneousOptions);

		internal static readonly SymbolDisplayFormat ShortWithTypeArgsAndContainingTypesFormat = new SymbolDisplayFormat(SymbolDisplayFormat.ShortFormat.GlobalNamespaceStyle, SymbolDisplayTypeQualificationStyle.NameAndContainingTypes, SymbolDisplayGenericsOptions.IncludeTypeParameters, SymbolDisplayFormat.ShortFormat.MemberOptions, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.Default, SymbolDisplayFormat.ShortFormat.ParameterOptions, SymbolDisplayFormat.ShortFormat.PropertyStyle, SymbolDisplayFormat.ShortFormat.LocalOptions, SymbolDisplayFormat.ShortFormat.KindOptions, SymbolDisplayFormat.ShortFormat.MiscellaneousOptions);

		public static FormattedSymbol QualifiedName(Symbol symbol)
		{
			return new FormattedSymbol(symbol, QualifiedNameFormat);
		}

		public static FormattedSymbol WithContainingType(Symbol symbol)
		{
			return new FormattedSymbol(symbol, WithContainingTypeFormat);
		}

		public static FormattedSymbol ErrorNameWithKind(Symbol symbol)
		{
			return new FormattedSymbol(symbol, ErrorNameWithKindFormat);
		}

		public static FormattedSymbol ShortErrorName(Symbol symbol)
		{
			return new FormattedSymbol(symbol, SymbolDisplayFormat.ShortFormat);
		}

		public static FormattedSymbol DelegateSignature(Symbol symbol)
		{
			return new FormattedSymbol(symbol, DelegateSignatureFormat);
		}

		public static FormattedSymbol ShortNameWithTypeArgs(Symbol symbol)
		{
			return new FormattedSymbol(symbol, ShortWithTypeArgsFormat);
		}

		public static FormattedSymbol ShortNameWithTypeArgsAndContainingTypes(Symbol symbol)
		{
			return new FormattedSymbol(symbol, ShortWithTypeArgsAndContainingTypesFormat);
		}

		public static FormattedSymbol DefaultErrorFormat(Symbol symbol)
		{
			return new FormattedSymbol(symbol, SymbolDisplayFormat.VisualBasicErrorMessageFormat);
		}
	}
}
