using System;

namespace Microsoft.CodeAnalysis.CSharp.Symbols
{
    [Flags()]
    internal enum CompletionPart
    {
        None = 0,
        Attributes = 1,
        ReturnTypeAttributes = 2,
        Parameters = 4,
        Type = 8,
        StartBaseType = 0x10,
        FinishBaseType = 0x20,
        StartInterfaces = 0x40,
        FinishInterfaces = 0x80,
        EnumUnderlyingType = 0x100,
        TypeArguments = 0x200,
        TypeParameters = 0x400,
        Members = 0x800,
        TypeMembers = 0x1000,
        SynthesizedExplicitImplementations = 0x2000,
        StartMemberChecks = 0x4000,
        FinishMemberChecks = 0x8000,
        MembersCompleted = 0x10000,
        All = 0x1FFFF,
        NamedTypeSymbolWithLocationAll = 0xFFF1,
        NamedTypeSymbolAll = 0x1FFF1,
        StartValidatingImports = 0x10,
        FinishValidatingImports = 0x20,
        ImportsAll = 0x30,
        NameToMembersMap = 0x800,
        NamespaceSymbolAll = 0x10800,
        FixedSize = 0x800,
        ConstantValue = 0x1000,
        FieldSymbolAll = 0x1809,
        StartAsyncMethodChecks = 0x800,
        FinishAsyncMethodChecks = 0x1000,
        StartMethodChecks = 0x2000,
        FinishMethodChecks = 0x4000,
        MethodSymbolAll = 0x7C0F,
        StartDefaultSyntaxValue = 0x800,
        EndDefaultSyntaxValue = 0x1000,
        EndDefaultSyntaxValueDiagnostics = 0x2000,
        ComplexParameterSymbolAll = 0x3801,
        TypeParameterConstraints = 0x800,
        TypeParameterSymbolAll = 0x801,
        StartPropertyEnsureSignature = 0x10,
        FinishPropertyEnsureSignature = 0x20,
        StartPropertyParameters = 0x40,
        FinishPropertyParameters = 0x80,
        StartPropertyType = 0x100,
        FinishPropertyType = 0x200,
        PropertySymbolAll = 0x3F1,
        AliasTarget = 0x10,
        StartAttributeChecks = 0x10,
        FinishAttributeChecks = 0x20,
        Module = 0x40,
        StartValidatingAddedModules = 0x100,
        FinishValidatingAddedModules = 0x200,
        AssemblySymbolAll = 0x371,
        StartValidatingReferencedAssemblies = 0x10,
        FinishValidatingReferencedAssemblies = 0x20
    }
}
