//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExtensions.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemExtensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a supported code page..
        /// </summary>
        internal static string Argument_CodepageNotSupported {
            get {
                return ResourceManager.GetString("Argument_CodepageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty name is not legal..
        /// </summary>
        internal static string Argument_EmptyName {
            get {
                return ResourceManager.GetString("Argument_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncoderFallbackNotEmpty {
            get {
                return ResourceManager.GetString("Argument_EncoderFallbackNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The output byte buffer is too small to contain the encoded data, encoding &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncodingConversionOverflowBytes {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The output char buffer is too small to contain the decoded characters, encoding &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncodingConversionOverflowChars {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String contains invalid Unicode code points..
        /// </summary>
        internal static string Argument_InvalidCharSequenceNoIndex {
            get {
                return ResourceManager.GetString("Argument_InvalidCharSequenceNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string Argument_InvalidOffLen {
            get {
                return ResourceManager.GetString("Argument_InvalidOffLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recursive fallback not allowed for character \\u{0:X4}..
        /// </summary>
        internal static string Argument_RecursiveFallback {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recursive fallback not allowed for bytes {0}..
        /// </summary>
        internal static string Argument_RecursiveFallbackBytes {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallbackBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Array cannot be null..
        /// </summary>
        internal static string ArgumentNull_Array {
            get {
                return ResourceManager.GetString("ArgumentNull_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buffer cannot be null..
        /// </summary>
        internal static string ArgumentNull_Buffer {
            get {
                return ResourceManager.GetString("ArgumentNull_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many characters. The resulting number of bytes is larger than what can be returned as an int..
        /// </summary>
        internal static string ArgumentOutOfRange_GetByteCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetByteCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many bytes. The resulting number of chars is larger than what can be returned as an int..
        /// </summary>
        internal static string ArgumentOutOfRange_GetCharCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetCharCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index and count must refer to a location within the string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCount {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index and count must refer to a location within the buffer..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCountBuffer {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCountBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non-negative number required..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valid values are between {0} and {1}, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_Range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The hash algorithm name cannot be null or empty..
        /// </summary>
        internal static string Cryptography_HashAlgorithmNameNullOrEmpty {
            get {
                return ResourceManager.GetString("Cryptography_HashAlgorithmNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The cipher mode specified requires that an initialization vector (IV) be used..
        /// </summary>
        internal static string Cryptography_MissingIV {
            get {
                return ResourceManager.GetString("Cryptography_MissingIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The provided hash value is not the expected size for the specified hash algorithm..
        /// </summary>
        internal static string Cryptography_SignHash_WrongSize {
            get {
                return ResourceManager.GetString("Cryptography_SignHash_WrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified PaddingMode is not supported..
        /// </summary>
        internal static string Cryptography_UnsupportedPaddingMode {
            get {
                return ResourceManager.GetString("Cryptography_UnsupportedPaddingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Western European (Mac).
        /// </summary>
        internal static string Globalization_cp_10000 {
            get {
                return ResourceManager.GetString("Globalization_cp_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (Mac).
        /// </summary>
        internal static string Globalization_cp_10001 {
            get {
                return ResourceManager.GetString("Globalization_cp_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Traditional (Mac).
        /// </summary>
        internal static string Globalization_cp_10002 {
            get {
                return ResourceManager.GetString("Globalization_cp_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Korean (Mac).
        /// </summary>
        internal static string Globalization_cp_10003 {
            get {
                return ResourceManager.GetString("Globalization_cp_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic (Mac).
        /// </summary>
        internal static string Globalization_cp_10004 {
            get {
                return ResourceManager.GetString("Globalization_cp_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hebrew (Mac).
        /// </summary>
        internal static string Globalization_cp_10005 {
            get {
                return ResourceManager.GetString("Globalization_cp_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greek (Mac).
        /// </summary>
        internal static string Globalization_cp_10006 {
            get {
                return ResourceManager.GetString("Globalization_cp_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyrillic (Mac).
        /// </summary>
        internal static string Globalization_cp_10007 {
            get {
                return ResourceManager.GetString("Globalization_cp_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (Mac).
        /// </summary>
        internal static string Globalization_cp_10008 {
            get {
                return ResourceManager.GetString("Globalization_cp_10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Romanian (Mac).
        /// </summary>
        internal static string Globalization_cp_10010 {
            get {
                return ResourceManager.GetString("Globalization_cp_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ukrainian (Mac).
        /// </summary>
        internal static string Globalization_cp_10017 {
            get {
                return ResourceManager.GetString("Globalization_cp_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thai (Mac).
        /// </summary>
        internal static string Globalization_cp_10021 {
            get {
                return ResourceManager.GetString("Globalization_cp_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central European (Mac).
        /// </summary>
        internal static string Globalization_cp_10029 {
            get {
                return ResourceManager.GetString("Globalization_cp_10029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icelandic (Mac).
        /// </summary>
        internal static string Globalization_cp_10079 {
            get {
                return ResourceManager.GetString("Globalization_cp_10079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turkish (Mac).
        /// </summary>
        internal static string Globalization_cp_10081 {
            get {
                return ResourceManager.GetString("Globalization_cp_10081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Croatian (Mac).
        /// </summary>
        internal static string Globalization_cp_10082 {
            get {
                return ResourceManager.GetString("Globalization_cp_10082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Turkish Latin-5).
        /// </summary>
        internal static string Globalization_cp_1026 {
            get {
                return ResourceManager.GetString("Globalization_cp_1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM Latin-1.
        /// </summary>
        internal static string Globalization_cp_1047 {
            get {
                return ResourceManager.GetString("Globalization_cp_1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (US-Canada-Euro).
        /// </summary>
        internal static string Globalization_cp_1140 {
            get {
                return ResourceManager.GetString("Globalization_cp_1140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Germany-Euro).
        /// </summary>
        internal static string Globalization_cp_1141 {
            get {
                return ResourceManager.GetString("Globalization_cp_1141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Denmark-Norway-Euro).
        /// </summary>
        internal static string Globalization_cp_1142 {
            get {
                return ResourceManager.GetString("Globalization_cp_1142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Finland-Sweden-Euro).
        /// </summary>
        internal static string Globalization_cp_1143 {
            get {
                return ResourceManager.GetString("Globalization_cp_1143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Italy-Euro).
        /// </summary>
        internal static string Globalization_cp_1144 {
            get {
                return ResourceManager.GetString("Globalization_cp_1144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Spain-Euro).
        /// </summary>
        internal static string Globalization_cp_1145 {
            get {
                return ResourceManager.GetString("Globalization_cp_1145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (UK-Euro).
        /// </summary>
        internal static string Globalization_cp_1146 {
            get {
                return ResourceManager.GetString("Globalization_cp_1146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (France-Euro).
        /// </summary>
        internal static string Globalization_cp_1147 {
            get {
                return ResourceManager.GetString("Globalization_cp_1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (International-Euro).
        /// </summary>
        internal static string Globalization_cp_1148 {
            get {
                return ResourceManager.GetString("Globalization_cp_1148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Icelandic-Euro).
        /// </summary>
        internal static string Globalization_cp_1149 {
            get {
                return ResourceManager.GetString("Globalization_cp_1149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central European (Windows).
        /// </summary>
        internal static string Globalization_cp_1250 {
            get {
                return ResourceManager.GetString("Globalization_cp_1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyrillic (Windows).
        /// </summary>
        internal static string Globalization_cp_1251 {
            get {
                return ResourceManager.GetString("Globalization_cp_1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Western European (Windows).
        /// </summary>
        internal static string Globalization_cp_1252 {
            get {
                return ResourceManager.GetString("Globalization_cp_1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greek (Windows).
        /// </summary>
        internal static string Globalization_cp_1253 {
            get {
                return ResourceManager.GetString("Globalization_cp_1253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turkish (Windows).
        /// </summary>
        internal static string Globalization_cp_1254 {
            get {
                return ResourceManager.GetString("Globalization_cp_1254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hebrew (Windows).
        /// </summary>
        internal static string Globalization_cp_1255 {
            get {
                return ResourceManager.GetString("Globalization_cp_1255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic (Windows).
        /// </summary>
        internal static string Globalization_cp_1256 {
            get {
                return ResourceManager.GetString("Globalization_cp_1256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baltic (Windows).
        /// </summary>
        internal static string Globalization_cp_1257 {
            get {
                return ResourceManager.GetString("Globalization_cp_1257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vietnamese (Windows).
        /// </summary>
        internal static string Globalization_cp_1258 {
            get {
                return ResourceManager.GetString("Globalization_cp_1258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Korean (Johab).
        /// </summary>
        internal static string Globalization_cp_1361 {
            get {
                return ResourceManager.GetString("Globalization_cp_1361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Traditional (CNS).
        /// </summary>
        internal static string Globalization_cp_20000 {
            get {
                return ResourceManager.GetString("Globalization_cp_20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TCA Taiwan.
        /// </summary>
        internal static string Globalization_cp_20001 {
            get {
                return ResourceManager.GetString("Globalization_cp_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Traditional (Eten).
        /// </summary>
        internal static string Globalization_cp_20002 {
            get {
                return ResourceManager.GetString("Globalization_cp_20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM5550 Taiwan.
        /// </summary>
        internal static string Globalization_cp_20003 {
            get {
                return ResourceManager.GetString("Globalization_cp_20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TeleText Taiwan.
        /// </summary>
        internal static string Globalization_cp_20004 {
            get {
                return ResourceManager.GetString("Globalization_cp_20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wang Taiwan.
        /// </summary>
        internal static string Globalization_cp_20005 {
            get {
                return ResourceManager.GetString("Globalization_cp_20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Western European (IA5).
        /// </summary>
        internal static string Globalization_cp_20105 {
            get {
                return ResourceManager.GetString("Globalization_cp_20105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à German (IA5).
        /// </summary>
        internal static string Globalization_cp_20106 {
            get {
                return ResourceManager.GetString("Globalization_cp_20106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swedish (IA5).
        /// </summary>
        internal static string Globalization_cp_20107 {
            get {
                return ResourceManager.GetString("Globalization_cp_20107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Norwegian (IA5).
        /// </summary>
        internal static string Globalization_cp_20108 {
            get {
                return ResourceManager.GetString("Globalization_cp_20108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T.61.
        /// </summary>
        internal static string Globalization_cp_20261 {
            get {
                return ResourceManager.GetString("Globalization_cp_20261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISO-6937.
        /// </summary>
        internal static string Globalization_cp_20269 {
            get {
                return ResourceManager.GetString("Globalization_cp_20269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Germany).
        /// </summary>
        internal static string Globalization_cp_20273 {
            get {
                return ResourceManager.GetString("Globalization_cp_20273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Denmark-Norway).
        /// </summary>
        internal static string Globalization_cp_20277 {
            get {
                return ResourceManager.GetString("Globalization_cp_20277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Finland-Sweden).
        /// </summary>
        internal static string Globalization_cp_20278 {
            get {
                return ResourceManager.GetString("Globalization_cp_20278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Italy).
        /// </summary>
        internal static string Globalization_cp_20280 {
            get {
                return ResourceManager.GetString("Globalization_cp_20280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Spain).
        /// </summary>
        internal static string Globalization_cp_20284 {
            get {
                return ResourceManager.GetString("Globalization_cp_20284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (UK).
        /// </summary>
        internal static string Globalization_cp_20285 {
            get {
                return ResourceManager.GetString("Globalization_cp_20285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Japanese katakana).
        /// </summary>
        internal static string Globalization_cp_20290 {
            get {
                return ResourceManager.GetString("Globalization_cp_20290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (France).
        /// </summary>
        internal static string Globalization_cp_20297 {
            get {
                return ResourceManager.GetString("Globalization_cp_20297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Arabic).
        /// </summary>
        internal static string Globalization_cp_20420 {
            get {
                return ResourceManager.GetString("Globalization_cp_20420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Greek).
        /// </summary>
        internal static string Globalization_cp_20423 {
            get {
                return ResourceManager.GetString("Globalization_cp_20423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Hebrew).
        /// </summary>
        internal static string Globalization_cp_20424 {
            get {
                return ResourceManager.GetString("Globalization_cp_20424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Korean Extended).
        /// </summary>
        internal static string Globalization_cp_20833 {
            get {
                return ResourceManager.GetString("Globalization_cp_20833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Thai).
        /// </summary>
        internal static string Globalization_cp_20838 {
            get {
                return ResourceManager.GetString("Globalization_cp_20838", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyrillic (KOI8-R).
        /// </summary>
        internal static string Globalization_cp_20866 {
            get {
                return ResourceManager.GetString("Globalization_cp_20866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Icelandic).
        /// </summary>
        internal static string Globalization_cp_20871 {
            get {
                return ResourceManager.GetString("Globalization_cp_20871", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Cyrillic Russian).
        /// </summary>
        internal static string Globalization_cp_20880 {
            get {
                return ResourceManager.GetString("Globalization_cp_20880", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Turkish).
        /// </summary>
        internal static string Globalization_cp_20905 {
            get {
                return ResourceManager.GetString("Globalization_cp_20905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM Latin-1.
        /// </summary>
        internal static string Globalization_cp_20924 {
            get {
                return ResourceManager.GetString("Globalization_cp_20924", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (JIS 0208-1990 and 0212-1990).
        /// </summary>
        internal static string Globalization_cp_20932 {
            get {
                return ResourceManager.GetString("Globalization_cp_20932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (GB2312-80).
        /// </summary>
        internal static string Globalization_cp_20936 {
            get {
                return ResourceManager.GetString("Globalization_cp_20936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Korean Wansung.
        /// </summary>
        internal static string Globalization_cp_20949 {
            get {
                return ResourceManager.GetString("Globalization_cp_20949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Cyrillic Serbian-Bulgarian).
        /// </summary>
        internal static string Globalization_cp_21025 {
            get {
                return ResourceManager.GetString("Globalization_cp_21025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ext Alpha Lowercase.
        /// </summary>
        internal static string Globalization_cp_21027 {
            get {
                return ResourceManager.GetString("Globalization_cp_21027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyrillic (KOI8-U).
        /// </summary>
        internal static string Globalization_cp_21866 {
            get {
                return ResourceManager.GetString("Globalization_cp_21866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central European (ISO).
        /// </summary>
        internal static string Globalization_cp_28592 {
            get {
                return ResourceManager.GetString("Globalization_cp_28592", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latin 3 (ISO).
        /// </summary>
        internal static string Globalization_cp_28593 {
            get {
                return ResourceManager.GetString("Globalization_cp_28593", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baltic (ISO).
        /// </summary>
        internal static string Globalization_cp_28594 {
            get {
                return ResourceManager.GetString("Globalization_cp_28594", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyrillic (ISO).
        /// </summary>
        internal static string Globalization_cp_28595 {
            get {
                return ResourceManager.GetString("Globalization_cp_28595", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic (ISO).
        /// </summary>
        internal static string Globalization_cp_28596 {
            get {
                return ResourceManager.GetString("Globalization_cp_28596", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greek (ISO).
        /// </summary>
        internal static string Globalization_cp_28597 {
            get {
                return ResourceManager.GetString("Globalization_cp_28597", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hebrew (ISO-Visual).
        /// </summary>
        internal static string Globalization_cp_28598 {
            get {
                return ResourceManager.GetString("Globalization_cp_28598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turkish (ISO).
        /// </summary>
        internal static string Globalization_cp_28599 {
            get {
                return ResourceManager.GetString("Globalization_cp_28599", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estonian (ISO).
        /// </summary>
        internal static string Globalization_cp_28603 {
            get {
                return ResourceManager.GetString("Globalization_cp_28603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latin 9 (ISO).
        /// </summary>
        internal static string Globalization_cp_28605 {
            get {
                return ResourceManager.GetString("Globalization_cp_28605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Europa.
        /// </summary>
        internal static string Globalization_cp_29001 {
            get {
                return ResourceManager.GetString("Globalization_cp_29001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (US-Canada).
        /// </summary>
        internal static string Globalization_cp_37 {
            get {
                return ResourceManager.GetString("Globalization_cp_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hebrew (ISO-Logical).
        /// </summary>
        internal static string Globalization_cp_38598 {
            get {
                return ResourceManager.GetString("Globalization_cp_38598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OEM United States.
        /// </summary>
        internal static string Globalization_cp_437 {
            get {
                return ResourceManager.GetString("Globalization_cp_437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (International).
        /// </summary>
        internal static string Globalization_cp_500 {
            get {
                return ResourceManager.GetString("Globalization_cp_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Defined.
        /// </summary>
        internal static string Globalization_cp_50000 {
            get {
                return ResourceManager.GetString("Globalization_cp_50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (JIS).
        /// </summary>
        internal static string Globalization_cp_50220 {
            get {
                return ResourceManager.GetString("Globalization_cp_50220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (JIS-Allow 1 byte Kana).
        /// </summary>
        internal static string Globalization_cp_50221 {
            get {
                return ResourceManager.GetString("Globalization_cp_50221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (JIS-Allow 1 byte Kana - SO/SI).
        /// </summary>
        internal static string Globalization_cp_50222 {
            get {
                return ResourceManager.GetString("Globalization_cp_50222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Korean (ISO).
        /// </summary>
        internal static string Globalization_cp_50225 {
            get {
                return ResourceManager.GetString("Globalization_cp_50225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (ISO-2022).
        /// </summary>
        internal static string Globalization_cp_50227 {
            get {
                return ResourceManager.GetString("Globalization_cp_50227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Traditional (ISO-2022).
        /// </summary>
        internal static string Globalization_cp_50229 {
            get {
                return ResourceManager.GetString("Globalization_cp_50229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Japanese and Japanese Katakana).
        /// </summary>
        internal static string Globalization_cp_50930 {
            get {
                return ResourceManager.GetString("Globalization_cp_50930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Japanese and US-Canada).
        /// </summary>
        internal static string Globalization_cp_50931 {
            get {
                return ResourceManager.GetString("Globalization_cp_50931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Korean and Korean Extended).
        /// </summary>
        internal static string Globalization_cp_50933 {
            get {
                return ResourceManager.GetString("Globalization_cp_50933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Simplified Chinese).
        /// </summary>
        internal static string Globalization_cp_50935 {
            get {
                return ResourceManager.GetString("Globalization_cp_50935", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Traditional Chinese).
        /// </summary>
        internal static string Globalization_cp_50937 {
            get {
                return ResourceManager.GetString("Globalization_cp_50937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Japanese and Japanese-Latin).
        /// </summary>
        internal static string Globalization_cp_50939 {
            get {
                return ResourceManager.GetString("Globalization_cp_50939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (EUC).
        /// </summary>
        internal static string Globalization_cp_51932 {
            get {
                return ResourceManager.GetString("Globalization_cp_51932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (EUC).
        /// </summary>
        internal static string Globalization_cp_51936 {
            get {
                return ResourceManager.GetString("Globalization_cp_51936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Korean (EUC).
        /// </summary>
        internal static string Globalization_cp_51949 {
            get {
                return ResourceManager.GetString("Globalization_cp_51949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (HZ).
        /// </summary>
        internal static string Globalization_cp_52936 {
            get {
                return ResourceManager.GetString("Globalization_cp_52936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (GB18030).
        /// </summary>
        internal static string Globalization_cp_54936 {
            get {
                return ResourceManager.GetString("Globalization_cp_54936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Devanagari.
        /// </summary>
        internal static string Globalization_cp_57002 {
            get {
                return ResourceManager.GetString("Globalization_cp_57002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Bengali.
        /// </summary>
        internal static string Globalization_cp_57003 {
            get {
                return ResourceManager.GetString("Globalization_cp_57003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Tamil.
        /// </summary>
        internal static string Globalization_cp_57004 {
            get {
                return ResourceManager.GetString("Globalization_cp_57004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Telugu.
        /// </summary>
        internal static string Globalization_cp_57005 {
            get {
                return ResourceManager.GetString("Globalization_cp_57005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Assamese.
        /// </summary>
        internal static string Globalization_cp_57006 {
            get {
                return ResourceManager.GetString("Globalization_cp_57006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Oriya.
        /// </summary>
        internal static string Globalization_cp_57007 {
            get {
                return ResourceManager.GetString("Globalization_cp_57007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Kannada.
        /// </summary>
        internal static string Globalization_cp_57008 {
            get {
                return ResourceManager.GetString("Globalization_cp_57008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Malayalam.
        /// </summary>
        internal static string Globalization_cp_57009 {
            get {
                return ResourceManager.GetString("Globalization_cp_57009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Gujarati.
        /// </summary>
        internal static string Globalization_cp_57010 {
            get {
                return ResourceManager.GetString("Globalization_cp_57010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISCII Punjabi.
        /// </summary>
        internal static string Globalization_cp_57011 {
            get {
                return ResourceManager.GetString("Globalization_cp_57011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic (ASMO 708).
        /// </summary>
        internal static string Globalization_cp_708 {
            get {
                return ResourceManager.GetString("Globalization_cp_708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic (DOS).
        /// </summary>
        internal static string Globalization_cp_720 {
            get {
                return ResourceManager.GetString("Globalization_cp_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greek (DOS).
        /// </summary>
        internal static string Globalization_cp_737 {
            get {
                return ResourceManager.GetString("Globalization_cp_737", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baltic (DOS).
        /// </summary>
        internal static string Globalization_cp_775 {
            get {
                return ResourceManager.GetString("Globalization_cp_775", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Western European (DOS).
        /// </summary>
        internal static string Globalization_cp_850 {
            get {
                return ResourceManager.GetString("Globalization_cp_850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central European (DOS).
        /// </summary>
        internal static string Globalization_cp_852 {
            get {
                return ResourceManager.GetString("Globalization_cp_852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OEM Cyrillic.
        /// </summary>
        internal static string Globalization_cp_855 {
            get {
                return ResourceManager.GetString("Globalization_cp_855", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turkish (DOS).
        /// </summary>
        internal static string Globalization_cp_857 {
            get {
                return ResourceManager.GetString("Globalization_cp_857", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OEM Multilingual Latin I.
        /// </summary>
        internal static string Globalization_cp_858 {
            get {
                return ResourceManager.GetString("Globalization_cp_858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portuguese (DOS).
        /// </summary>
        internal static string Globalization_cp_860 {
            get {
                return ResourceManager.GetString("Globalization_cp_860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icelandic (DOS).
        /// </summary>
        internal static string Globalization_cp_861 {
            get {
                return ResourceManager.GetString("Globalization_cp_861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hebrew (DOS).
        /// </summary>
        internal static string Globalization_cp_862 {
            get {
                return ResourceManager.GetString("Globalization_cp_862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French Canadian (DOS).
        /// </summary>
        internal static string Globalization_cp_863 {
            get {
                return ResourceManager.GetString("Globalization_cp_863", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic (864).
        /// </summary>
        internal static string Globalization_cp_864 {
            get {
                return ResourceManager.GetString("Globalization_cp_864", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nordic (DOS).
        /// </summary>
        internal static string Globalization_cp_865 {
            get {
                return ResourceManager.GetString("Globalization_cp_865", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyrillic (DOS).
        /// </summary>
        internal static string Globalization_cp_866 {
            get {
                return ResourceManager.GetString("Globalization_cp_866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greek, Modern (DOS).
        /// </summary>
        internal static string Globalization_cp_869 {
            get {
                return ResourceManager.GetString("Globalization_cp_869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Multilingual Latin-2).
        /// </summary>
        internal static string Globalization_cp_870 {
            get {
                return ResourceManager.GetString("Globalization_cp_870", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thai (Windows).
        /// </summary>
        internal static string Globalization_cp_874 {
            get {
                return ResourceManager.GetString("Globalization_cp_874", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBM EBCDIC (Greek Modern).
        /// </summary>
        internal static string Globalization_cp_875 {
            get {
                return ResourceManager.GetString("Globalization_cp_875", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese (Shift-JIS).
        /// </summary>
        internal static string Globalization_cp_932 {
            get {
                return ResourceManager.GetString("Globalization_cp_932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Simplified (GB2312).
        /// </summary>
        internal static string Globalization_cp_936 {
            get {
                return ResourceManager.GetString("Globalization_cp_936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Korean.
        /// </summary>
        internal static string Globalization_cp_949 {
            get {
                return ResourceManager.GetString("Globalization_cp_949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Traditional (Big5).
        /// </summary>
        internal static string Globalization_cp_950 {
            get {
                return ResourceManager.GetString("Globalization_cp_950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find a resource entry for the encoding codepage &apos;{0} - {1}&apos;.
        /// </summary>
        internal static string MissingEncodingNameResource {
            get {
                return ResourceManager.GetString("MissingEncodingNameResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data is available for encoding {0}..
        /// </summary>
        internal static string NotSupported_NoCodepageData {
            get {
                return ResourceManager.GetString("NotSupported_NoCodepageData", resourceCulture);
            }
        }
    }
}
