Imports Microsoft.CodeAnalysis
Imports System

Namespace Microsoft.CodeAnalysis.VisualBasic
	Friend Class CustomSymbolDisplayFormatter
		Friend ReadOnly Shared QualifiedNameFormat As SymbolDisplayFormat

		Friend ReadOnly Shared WithContainingTypeFormat As SymbolDisplayFormat

		Friend ReadOnly Shared ErrorMessageFormatNoModifiersNoReturnType As SymbolDisplayFormat

		Friend ReadOnly Shared ErrorNameWithKindFormat As SymbolDisplayFormat

		Friend ReadOnly Shared DelegateSignatureFormat As SymbolDisplayFormat

		Friend ReadOnly Shared ShortWithTypeArgsFormat As SymbolDisplayFormat

		Friend ReadOnly Shared ShortWithTypeArgsAndContainingTypesFormat As SymbolDisplayFormat

		Shared Sub New()
			CustomSymbolDisplayFormatter.QualifiedNameFormat = New SymbolDisplayFormat(SymbolDisplayGlobalNamespaceStyle.Omitted, SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces, SymbolDisplayGenericsOptions.IncludeTypeParameters, SymbolDisplayMemberOptions.IncludeParameters Or SymbolDisplayMemberOptions.IncludeContainingType, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayParameterOptions.IncludeParamsRefOut Or SymbolDisplayParameterOptions.IncludeType Or SymbolDisplayParameterOptions.IncludeName Or SymbolDisplayParameterOptions.IncludeDefaultValue, SymbolDisplayPropertyStyle.NameOnly, SymbolDisplayLocalOptions.None, SymbolDisplayKindOptions.None, SymbolDisplayMiscellaneousOptions.UseSpecialTypes Or SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers)
			CustomSymbolDisplayFormatter.WithContainingTypeFormat = New SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.TypeQualificationStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.GenericsOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MemberOptions Or SymbolDisplayMemberOptions.IncludeContainingType, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayFormat.VisualBasicErrorMessageFormat.ParameterOptions, SymbolDisplayPropertyStyle.NameOnly, SymbolDisplayLocalOptions.None, SymbolDisplayFormat.VisualBasicErrorMessageFormat.KindOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions)
			CustomSymbolDisplayFormatter.ErrorMessageFormatNoModifiersNoReturnType = New SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.TypeQualificationStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.GenericsOptions, SymbolDisplayMemberOptions.IncludeExplicitInterface Or SymbolDisplayMemberOptions.IncludeParameters Or SymbolDisplayMemberOptions.IncludeContainingType, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayFormat.VisualBasicErrorMessageFormat.ParameterOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.PropertyStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.LocalOptions, SymbolDisplayKindOptions.None, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions)
			CustomSymbolDisplayFormatter.ErrorNameWithKindFormat = New SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayTypeQualificationStyle.NameOnly, SymbolDisplayFormat.VisualBasicErrorMessageFormat.GenericsOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MemberOptions, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayFormat.VisualBasicErrorMessageFormat.ParameterOptions, SymbolDisplayFormat.VisualBasicErrorMessageFormat.PropertyStyle, SymbolDisplayFormat.VisualBasicErrorMessageFormat.LocalOptions, SymbolDisplayKindOptions.IncludeNamespaceKeyword Or SymbolDisplayKindOptions.IncludeTypeKeyword, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions)
			CustomSymbolDisplayFormatter.DelegateSignatureFormat = New SymbolDisplayFormat(SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.GlobalNamespaceStyle, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.TypeQualificationStyle, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.GenericsOptions, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.MemberOptions, SymbolDisplayDelegateStyle.NameAndSignature, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.ParameterOptions, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.PropertyStyle, SymbolDisplayFormat.VisualBasicShortErrorMessageFormat.LocalOptions, SymbolDisplayKindOptions.IncludeNamespaceKeyword Or SymbolDisplayKindOptions.IncludeTypeKeyword, SymbolDisplayFormat.VisualBasicErrorMessageFormat.MiscellaneousOptions)
			CustomSymbolDisplayFormatter.ShortWithTypeArgsFormat = New SymbolDisplayFormat(SymbolDisplayFormat.ShortFormat.GlobalNamespaceStyle, SymbolDisplayFormat.ShortFormat.TypeQualificationStyle, SymbolDisplayGenericsOptions.IncludeTypeParameters, SymbolDisplayFormat.ShortFormat.MemberOptions, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayFormat.ShortFormat.ParameterOptions, SymbolDisplayFormat.ShortFormat.PropertyStyle, SymbolDisplayFormat.ShortFormat.LocalOptions, SymbolDisplayFormat.ShortFormat.KindOptions, SymbolDisplayFormat.ShortFormat.MiscellaneousOptions)
			CustomSymbolDisplayFormatter.ShortWithTypeArgsAndContainingTypesFormat = New SymbolDisplayFormat(SymbolDisplayFormat.ShortFormat.GlobalNamespaceStyle, SymbolDisplayTypeQualificationStyle.NameAndContainingTypes, SymbolDisplayGenericsOptions.IncludeTypeParameters, SymbolDisplayFormat.ShortFormat.MemberOptions, SymbolDisplayDelegateStyle.NameOnly, SymbolDisplayExtensionMethodStyle.[Default], SymbolDisplayFormat.ShortFormat.ParameterOptions, SymbolDisplayFormat.ShortFormat.PropertyStyle, SymbolDisplayFormat.ShortFormat.LocalOptions, SymbolDisplayFormat.ShortFormat.KindOptions, SymbolDisplayFormat.ShortFormat.MiscellaneousOptions)
		End Sub

		Public Sub New()
			MyBase.New()
		End Sub

		Public Shared Function DefaultErrorFormat(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, SymbolDisplayFormat.VisualBasicErrorMessageFormat)
		End Function

		Public Shared Function DelegateSignature(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, CustomSymbolDisplayFormatter.DelegateSignatureFormat)
		End Function

		Public Shared Function ErrorNameWithKind(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, CustomSymbolDisplayFormatter.ErrorNameWithKindFormat)
		End Function

		Public Shared Function QualifiedName(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, CustomSymbolDisplayFormatter.QualifiedNameFormat)
		End Function

		Public Shared Function ShortErrorName(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, SymbolDisplayFormat.ShortFormat)
		End Function

		Public Shared Function ShortNameWithTypeArgs(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, CustomSymbolDisplayFormatter.ShortWithTypeArgsFormat)
		End Function

		Public Shared Function ShortNameWithTypeArgsAndContainingTypes(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, CustomSymbolDisplayFormatter.ShortWithTypeArgsAndContainingTypesFormat)
		End Function

		Public Shared Function WithContainingType(ByVal symbol As Microsoft.CodeAnalysis.VisualBasic.Symbol) As FormattedSymbol
			Return New FormattedSymbol(symbol, CustomSymbolDisplayFormatter.WithContainingTypeFormat)
		End Function
	End Class
End Namespace