//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.Scripting.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.Scripting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Absolute path expected.
        /// </summary>
        internal static string AbsolutePathExpected {
            get {
                return ResourceManager.GetString("AbsolutePathExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly &apos;{0}, Version={1}&apos; has already been loaded from &apos;{2}&apos;. A different assembly with the same name and version can&apos;t be loaded: &apos;{3}&apos;..
        /// </summary>
        internal static string AssemblyAlreadyLoaded {
            get {
                return ResourceManager.GetString("AssemblyAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly &apos;{0}&apos; has already been loaded from &apos;{1}&apos;. A different assembly with the same name can&apos;t be loaded unless it&apos;s signed: &apos;{2}&apos;..
        /// </summary>
        internal static string AssemblyAlreadyLoadedNotSigned {
            get {
                return ResourceManager.GetString("AssemblyAlreadyLoadedNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  at {0} : {1}.
        /// </summary>
        internal static string AtFileLine {
            get {
                return ResourceManager.GetString("AtFileLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot set a constant variable.
        /// </summary>
        internal static string CannotSetConstantVariable {
            get {
                return ResourceManager.GetString("CannotSetConstantVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot set {0} specific option {1} because the options were already configured for a different language..
        /// </summary>
        internal static string CannotSetLanguageSpecificOption {
            get {
                return ResourceManager.GetString("CannotSetLanguageSpecificOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot set a read-only variable.
        /// </summary>
        internal static string CannotSetReadOnlyVariable {
            get {
                return ResourceManager.GetString("CannotSetReadOnlyVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t assign &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CantAssignTo {
            get {
                return ResourceManager.GetString("CantAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display name or path cannot be empty..
        /// </summary>
        internal static string DisplayNameOrPathCannotBe {
            get {
                return ResourceManager.GetString("DisplayNameOrPathCannotBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expected an assembly reference..
        /// </summary>
        internal static string ExpectedAnAssemblyReference {
            get {
                return ResourceManager.GetString("ExpectedAnAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The globals of type &apos;{0}&apos; is not assignable to &apos;{1}&apos;.
        /// </summary>
        internal static string GlobalsNotAssignable {
            get {
                return ResourceManager.GetString("GlobalsNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global variables passed to a script without a global type.
        /// </summary>
        internal static string GlobalVariablesWithoutGlobalType {
            get {
                return ResourceManager.GetString("GlobalVariablesWithoutGlobalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type &quot;#help&quot; for more information..
        /// </summary>
        internal static string HelpPrompt {
            get {
                return ResourceManager.GetString("HelpPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard shortcuts:
        ///  Enter         If the current submission appears to be complete, evaluate it.  Otherwise, insert a new line.
        ///  Escape        Clear the current submission.
        ///  UpArrow       Replace the current submission with a previous submission.
        ///  DownArrow     Replace the current submission with a subsequent submission (after having previously navigated backwards).
        ///  Ctrl-C        Exit the REPL.
        ///REPL commands:
        ///  #help         Display help on available commands and key bindings.
        ///Script directiv [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid assembly name.
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid characters in assemblyName.
        /// </summary>
        internal static string InvalidCharactersInAssemblyName {
            get {
                return ResourceManager.GetString("InvalidCharactersInAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à + additional {0} error.
        /// </summary>
        internal static string PlusAdditionalError {
            get {
                return ResourceManager.GetString("PlusAdditionalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à + additional {0} errors.
        /// </summary>
        internal static string PlusAdditionalErrors {
            get {
                return ResourceManager.GetString("PlusAdditionalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The script requires access to global variables but none were given.
        /// </summary>
        internal static string ScriptRequiresGlobalVariables {
            get {
                return ResourceManager.GetString("ScriptRequiresGlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à !&amp;lt;Stack overflow while evaluating object&amp;gt;.
        /// </summary>
        internal static string StackOverflowWhileEvaluating {
            get {
                return ResourceManager.GetString("StackOverflowWhileEvaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting state was incompatible with script..
        /// </summary>
        internal static string StartingStateIncompatible {
            get {
                return ResourceManager.GetString("StartingStateIncompatible", resourceCulture);
            }
        }
    }
}
